/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'id' : bigint,
  'status' : { 'canceled' : null } |
    { 'pending' : null } |
    { 'completed' : null } |
    { 'confirmed' : null },
  'serviceCategory' : string,
  'name' : string,
  'preferredDate' : string,
  'address' : string,
  'notes' : string,
  'timestamp' : Time,
  'phone' : string,
  'timeSlot' : string,
}
export interface ContactMessage {
  'id' : bigint,
  'status' : { 'read' : null } |
    { 'unread' : null },
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
  'phone' : string,
  'services' : string,
}
export interface PartnerApplication {
  'id' : bigint,
  'status' : { 'pending' : null } |
    { 'approved' : null } |
    { 'rejected' : null },
  'documents' : string,
  'city' : string,
  'name' : string,
  'timestamp' : Time,
  'phone' : string,
  'skills' : string,
}
export interface ServiceCategory {
  'name' : string,
  'description' : string,
  'basePrice' : bigint,
}
export interface Statistics {
  'pendingBookings' : bigint,
  'totalBookings' : bigint,
  'totalMessages' : bigint,
  'totalPartners' : bigint,
  'completedBookings' : bigint,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllBookings' : ActorMethod<[], Array<Booking>>,
  'getAllContactMessages' : ActorMethod<[], Array<ContactMessage>>,
  'getAllPartnerApplications' : ActorMethod<[], Array<PartnerApplication>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPlatformStatistics' : ActorMethod<[], Statistics>,
  'getServiceCategories' : ActorMethod<[], Array<ServiceCategory>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initialize' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markContactMessageAsRead' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitBooking' : ActorMethod<
    [string, string, string, string, string, string, string],
    bigint
  >,
  'submitContactMessage' : ActorMethod<
    [string, string, string, string, string],
    bigint
  >,
  'submitPartnerApplication' : ActorMethod<
    [string, string, string, string, string],
    bigint
  >,
  'updateBookingStatus' : ActorMethod<
    [
      bigint,
      { 'canceled' : null } |
        { 'pending' : null } |
        { 'completed' : null } |
        { 'confirmed' : null },
    ],
    undefined
  >,
  'updatePartnerApplicationStatus' : ActorMethod<
    [
      bigint,
      { 'pending' : null } |
        { 'approved' : null } |
        { 'rejected' : null },
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];