/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const Booking = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Variant({
    'canceled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'confirmed' : IDL.Null,
  }),
  'serviceCategory' : IDL.Text,
  'name' : IDL.Text,
  'preferredDate' : IDL.Text,
  'address' : IDL.Text,
  'notes' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Text,
  'timeSlot' : IDL.Text,
});
export const ContactMessage = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Variant({ 'read' : IDL.Null, 'unread' : IDL.Null }),
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Text,
  'services' : IDL.Text,
});
export const PartnerApplication = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  }),
  'documents' : IDL.Text,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Text,
  'skills' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Statistics = IDL.Record({
  'pendingBookings' : IDL.Nat,
  'totalBookings' : IDL.Nat,
  'totalMessages' : IDL.Nat,
  'totalPartners' : IDL.Nat,
  'completedBookings' : IDL.Nat,
});
export const ServiceCategory = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'basePrice' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getAllContactMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], ['query']),
  'getAllPartnerApplications' : IDL.Func(
      [],
      [IDL.Vec(PartnerApplication)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPlatformStatistics' : IDL.Func([], [Statistics], ['query']),
  'getServiceCategories' : IDL.Func([], [IDL.Vec(ServiceCategory)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initialize' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markContactMessageAsRead' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitBooking' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'submitContactMessage' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'submitPartnerApplication' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'updateBookingStatus' : IDL.Func(
      [
        IDL.Nat,
        IDL.Variant({
          'canceled' : IDL.Null,
          'pending' : IDL.Null,
          'completed' : IDL.Null,
          'confirmed' : IDL.Null,
        }),
      ],
      [],
      [],
    ),
  'updatePartnerApplicationStatus' : IDL.Func(
      [
        IDL.Nat,
        IDL.Variant({
          'pending' : IDL.Null,
          'approved' : IDL.Null,
          'rejected' : IDL.Null,
        }),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const Booking = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Variant({
      'canceled' : IDL.Null,
      'pending' : IDL.Null,
      'completed' : IDL.Null,
      'confirmed' : IDL.Null,
    }),
    'serviceCategory' : IDL.Text,
    'name' : IDL.Text,
    'preferredDate' : IDL.Text,
    'address' : IDL.Text,
    'notes' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Text,
    'timeSlot' : IDL.Text,
  });
  const ContactMessage = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Variant({ 'read' : IDL.Null, 'unread' : IDL.Null }),
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Text,
    'services' : IDL.Text,
  });
  const PartnerApplication = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Variant({
      'pending' : IDL.Null,
      'approved' : IDL.Null,
      'rejected' : IDL.Null,
    }),
    'documents' : IDL.Text,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Text,
    'skills' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Statistics = IDL.Record({
    'pendingBookings' : IDL.Nat,
    'totalBookings' : IDL.Nat,
    'totalMessages' : IDL.Nat,
    'totalPartners' : IDL.Nat,
    'completedBookings' : IDL.Nat,
  });
  const ServiceCategory = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'basePrice' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getAllContactMessages' : IDL.Func(
        [],
        [IDL.Vec(ContactMessage)],
        ['query'],
      ),
    'getAllPartnerApplications' : IDL.Func(
        [],
        [IDL.Vec(PartnerApplication)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPlatformStatistics' : IDL.Func([], [Statistics], ['query']),
    'getServiceCategories' : IDL.Func(
        [],
        [IDL.Vec(ServiceCategory)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initialize' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markContactMessageAsRead' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitBooking' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'submitContactMessage' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'submitPartnerApplication' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'updateBookingStatus' : IDL.Func(
        [
          IDL.Nat,
          IDL.Variant({
            'canceled' : IDL.Null,
            'pending' : IDL.Null,
            'completed' : IDL.Null,
            'confirmed' : IDL.Null,
          }),
        ],
        [],
        [],
      ),
    'updatePartnerApplicationStatus' : IDL.Func(
        [
          IDL.Nat,
          IDL.Variant({
            'pending' : IDL.Null,
            'approved' : IDL.Null,
            'rejected' : IDL.Null,
          }),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };